/*
 * materialCalc
 * Copyright (C) 2026 M415X
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.m415x.materialcalc.ui.theme

import androidx.compose.ui.graphics.Color

data object ThemeSecurityColors {

    // Light
    val primaryLight = Color(0xFF034B72)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF2A638B)
    val onPrimaryContainerLight = Color(0xFFB8DDFF)
    val secondaryLight = Color(0xFF9F4200)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFFF6D00)
    val onSecondaryContainerLight = Color(0xFF582100)
    val tertiaryLight = Color(0xFF006E2A)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF00C853)
    val onTertiaryContainerLight = Color(0xFF004C1B)
    val errorLight = Color(0xFFBC0100)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFEB0000)
    val onErrorContainerLight = Color(0xFFFFFBFF)
    val backgroundLight = Color(0xFFF8F9FD)
    val onBackgroundLight = Color(0xFF191C1F)
    val surfaceLight = Color(0xFFFCF8F8)
    val onSurfaceLight = Color(0xFF1C1B1B)
    val surfaceVariantLight = Color(0xFFDDE3EB)
    val onSurfaceVariantLight = Color(0xFF41474E)
    val outlineLight = Color(0xFF71787F)
    val outlineVariantLight = Color(0xFFC1C7CF)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF313030)
    val inverseOnSurfaceLight = Color(0xFFF3F0EF)
    val inversePrimaryLight = Color(0xFF97CCF9)
    val surfaceDimLight = Color(0xFFDCD9D9)
    val surfaceBrightLight = Color(0xFFFCF8F8)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF6F3F2)
    val surfaceContainerLight = Color(0xFFF1EDEC)
    val surfaceContainerHighLight = Color(0xFFEBE7E7)
    val surfaceContainerHighestLight = Color(0xFFE5E2E1)
    val warningLight = Color(0xFF8B5000)
    val onWarningLight = Color(0xFFFFFFFF)
    val warningContainerLight = Color(0xFFFF9800)
    val onWarningContainerLight = Color(0xFF653900)

    // Light High Contrast
    val primaryLightHighContrast = Color(0xFF002F4A)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF084D74)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF4F1D00)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF7D3200)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF003410)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF00551F)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600000)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF980100)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF8F9FD)
    val onBackgroundLightHighContrast = Color(0xFF191C1F)
    val surfaceLightHighContrast = Color(0xFFFCF8F8)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFDDE3EB)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF262D33)
    val outlineVariantLightHighContrast = Color(0xFF434A50)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF313030)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFF97CCF9)
    val surfaceDimLightHighContrast = Color(0xFFBBB8B8)
    val surfaceBrightLightHighContrast = Color(0xFFFCF8F8)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF3F0EF)
    val surfaceContainerLightHighContrast = Color(0xFFE5E2E1)
    val surfaceContainerHighLightHighContrast = Color(0xFFD7D4D3)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC9C6C5)
    val warningLightHighContrast = Color(0xFF442500)
    val onWarningLightHighContrast = Color(0xFFFFFFFF)
    val warningContainerLightHighContrast = Color(0xFF6D3E00)
    val onWarningContainerLightHighContrast = Color(0xFFFFFFFF)

    // Dark
    val primaryDark = Color(0xFF97CCF9)
    val onPrimaryDark = Color(0xFF003350)
    val primaryContainerDark = Color(0xFF2A638B)
    val onPrimaryContainerDark = Color(0xFFB8DDFF)
    val secondaryDark = Color(0xFFFFB692)
    val onSecondaryDark = Color(0xFF562000)
    val secondaryContainerDark = Color(0xFFFF6D00)
    val onSecondaryContainerDark = Color(0xFF582100)
    val tertiaryDark = Color(0xFF3FE56C)
    val onTertiaryDark = Color(0xFF003912)
    val tertiaryContainerDark = Color(0xFF00C853)
    val onTertiaryContainerDark = Color(0xFF004C1B)
    val errorDark = Color(0xFFFFB4A8)
    val onErrorDark = Color(0xFF690100)
    val errorContainerDark = Color(0xFFFF5540)
    val onErrorContainerDark = Color(0xFF360000)
    val backgroundDark = Color(0xFF111416)
    val onBackgroundDark = Color(0xFFE1E2E6)
    val surfaceDark = Color(0xFF131313)
    val onSurfaceDark = Color(0xFFE5E2E1)
    val surfaceVariantDark = Color(0xFF41474E)
    val onSurfaceVariantDark = Color(0xFFC1C7CF)
    val outlineDark = Color(0xFF8B9199)
    val outlineVariantDark = Color(0xFF41474E)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE5E2E1)
    val inverseOnSurfaceDark = Color(0xFF313030)
    val inversePrimaryDark = Color(0xFF2A638B)
    val surfaceDimDark = Color(0xFF131313)
    val surfaceBrightDark = Color(0xFF3A3939)
    val surfaceContainerLowestDark = Color(0xFF0E0E0E)
    val surfaceContainerLowDark = Color(0xFF1C1B1B)
    val surfaceContainerDark = Color(0xFF201F1F)
    val surfaceContainerHighDark = Color(0xFF2A2A2A)
    val surfaceContainerHighestDark = Color(0xFF353434)
    val warningDark = Color(0xFFFFC081)
    val onWarningDark = Color(0xFF4A2800)
    val warningContainerDark = Color(0xFFFF9800)
    val onWarningContainerDark = Color(0xFF653900)

    // Dark High Contrast
    val primaryDarkHighContrast = Color(0xFFE5F1FF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF94C8F5)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000C18)
    val secondaryDarkHighContrast = Color(0xFFFFECE5)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFFFB08A)
    val onSecondaryContainerDarkHighContrast = Color(0xFF1A0500)
    val tertiaryDarkHighContrast = Color(0xFFC2FFC3)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFF36DE66)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000F02)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA1)
    val onErrorContainerDarkHighContrast = Color(0xFF220000)
    val backgroundDarkHighContrast = Color(0xFF111416)
    val onBackgroundDarkHighContrast = Color(0xFFE1E2E6)
    val surfaceDarkHighContrast = Color(0xFF131313)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF41474E)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFEBF0F9)
    val outlineVariantDarkHighContrast = Color(0xFFBDC3CB)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E1)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF054C73)
    val surfaceDimDarkHighContrast = Color(0xFF131313)
    val surfaceBrightDarkHighContrast = Color(0xFF515050)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF201F1F)
    val surfaceContainerDarkHighContrast = Color(0xFF313030)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3B)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF474646)
    val warningDarkHighContrast = Color(0xFFFFEDDF)
    val onWarningDarkHighContrast = Color(0xFF000000)
    val warningContainerDarkHighContrast = Color(0xFFFFB363)
    val onWarningContainerDarkHighContrast = Color(0xFF150800)
}