/*
 * materialCalc
 * Copyright (C) 2026 M415X
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.m415x.materialcalc.ui.theme

import androidx.compose.ui.graphics.Color

data object ThemeIndustrialColors {

    // Light
    val primaryLight = Color(0xFF12531B)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF2E6C31)
    val onPrimaryContainerLight = Color(0xFFA7EBA1)
    val secondaryLight = Color(0xFF8D4933)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFAB6049)
    val onSecondaryContainerLight = Color(0xFFFFFBFF)
    val tertiaryLight = Color(0xFF8B5000)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFF2A34F)
    val onTertiaryContainerLight = Color(0xFF683B00)
    val errorLight = Color(0xFF930009)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFBA1A1A)
    val onErrorContainerLight = Color(0xFFFFCDC7)
    val backgroundLight = Color(0xFFF8FAF2)
    val onBackgroundLight = Color(0xFF191D18)
    val surfaceLight = Color(0xFFFCF9F7)
    val onSurfaceLight = Color(0xFF1C1B1B)
    val surfaceVariantLight = Color(0xFFE0E3DD)
    val onSurfaceVariantLight = Color(0xFF444843)
    val outlineLight = Color(0xFF747873)
    val outlineVariantLight = Color(0xFFC4C7C2)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF313030)
    val inverseOnSurfaceLight = Color(0xFFF4F0EF)
    val inversePrimaryLight = Color(0xFF94D78F)
    val surfaceDimLight = Color(0xFFDDD9D8)
    val surfaceBrightLight = Color(0xFFFCF9F7)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF6F3F1)
    val surfaceContainerLight = Color(0xFFF1EDEC)
    val surfaceContainerHighLight = Color(0xFFEBE7E6)
    val surfaceContainerHighestLight = Color(0xFFE5E2E0)
    val warningLight = Color(0xFF8B5000)
    val onWarningLight = Color(0xFFFFFFFF)
    val warningContainerLight = Color(0xFFFF9800)
    val onWarningContainerLight = Color(0xFF653900)

    // Light High Contrast
    val primaryLightHighContrast = Color(0xFF00340A)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF14551D)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF511B09)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF763722)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF442500)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF6D3E00)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF8FAF2)
    val onBackgroundLightHighContrast = Color(0xFF191D18)
    val surfaceLightHighContrast = Color(0xFFFCF9F7)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFE0E3DD)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF292D29)
    val outlineVariantLightHighContrast = Color(0xFF464A46)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF313030)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFF94D78F)
    val surfaceDimLightHighContrast = Color(0xFFBBB8B7)
    val surfaceBrightLightHighContrast = Color(0xFFFCF9F7)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF4F0EF)
    val surfaceContainerLightHighContrast = Color(0xFFE5E2E0)
    val surfaceContainerHighLightHighContrast = Color(0xFFD7D4D2)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC9C6C5)
    val warningLightHighContrast = Color(0xFF442500)
    val onWarningLightHighContrast = Color(0xFFFFFFFF)
    val warningContainerLightHighContrast = Color(0xFF6D3E00)
    val onWarningContainerLightHighContrast = Color(0xFFFFFFFF)

    // Dark
    val primaryDark = Color(0xFF94D78F)
    val onPrimaryDark = Color(0xFF00390B)
    val primaryContainerDark = Color(0xFF2E6C31)
    val onPrimaryContainerDark = Color(0xFFA7EBA1)
    val secondaryDark = Color(0xFFFFB59E)
    val onSecondaryDark = Color(0xFF561F0C)
    val secondaryContainerDark = Color(0xFFCC7C63)
    val onSecondaryContainerDark = Color(0xFF310800)
    val tertiaryDark = Color(0xFFFFC48C)
    val onTertiaryDark = Color(0xFF4A2800)
    val tertiaryContainerDark = Color(0xFFF2A34F)
    val onTertiaryContainerDark = Color(0xFF683B00)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690004)
    val errorContainerDark = Color(0xFFBA1A1A)
    val onErrorContainerDark = Color(0xFFFFCDC7)
    val backgroundDark = Color(0xFF111410)
    val onBackgroundDark = Color(0xFFE1E4DB)
    val surfaceDark = Color(0xFF141313)
    val onSurfaceDark = Color(0xFFE5E2E0)
    val surfaceVariantDark = Color(0xFF444843)
    val onSurfaceVariantDark = Color(0xFFC4C7C2)
    val outlineDark = Color(0xFF8E928C)
    val outlineVariantDark = Color(0xFF444843)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE5E2E0)
    val inverseOnSurfaceDark = Color(0xFF313030)
    val inversePrimaryDark = Color(0xFF2D6B30)
    val surfaceDimDark = Color(0xFF141313)
    val surfaceBrightDark = Color(0xFF3A3938)
    val surfaceContainerLowestDark = Color(0xFF0E0E0E)
    val surfaceContainerLowDark = Color(0xFF1C1B1B)
    val surfaceContainerDark = Color(0xFF201F1F)
    val surfaceContainerHighDark = Color(0xFF2A2A29)
    val surfaceContainerHighestDark = Color(0xFF353534)
    val warningDark = Color(0xFFFFC081)
    val onWarningDark = Color(0xFF4A2800)
    val warningContainerDark = Color(0xFFFF9800)
    val onWarningContainerDark = Color(0xFF653900)

    // Dark High Contrast
    val primaryDarkHighContrast = Color(0xFFC4FFBD)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF90D38C)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000F01)
    val secondaryDarkHighContrast = Color(0xFFFFECE7)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFFFAF97)
    val onSecondaryContainerDarkHighContrast = Color(0xFF1E0300)
    val tertiaryDarkHighContrast = Color(0xFFFFEDDF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFFFB364)
    val onTertiaryContainerDarkHighContrast = Color(0xFF150800)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220000)
    val backgroundDarkHighContrast = Color(0xFF111410)
    val onBackgroundDarkHighContrast = Color(0xFFE1E4DB)
    val surfaceDarkHighContrast = Color(0xFF141313)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF444843)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFEEF1EB)
    val outlineVariantDarkHighContrast = Color(0xFFC0C4BE)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E0)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF13531B)
    val surfaceDimDarkHighContrast = Color(0xFF141313)
    val surfaceBrightDarkHighContrast = Color(0xFF51504F)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF201F1F)
    val surfaceContainerDarkHighContrast = Color(0xFF313030)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3B)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF474646)
    val warningDarkHighContrast = Color(0xFFFFEDDF)
    val onWarningDarkHighContrast = Color(0xFF000000)
    val warningContainerDarkHighContrast = Color(0xFFFFB363)
    val onWarningContainerDarkHighContrast = Color(0xFF150800)
}