/*
 * materialCalc
 * Copyright (C) 2026 M415X
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.m415x.materialcalc.ui.theme

import androidx.compose.ui.graphics.Color

data object ThemeDefaultColors{

    // Light
    val primaryLight = Color(0xFF2A638B)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFCCE5FF)
    val onPrimaryContainerLight = Color(0xFF044B71)
    val secondaryLight = Color(0xFF006A6A)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFF9CF1F0)
    val onSecondaryContainerLight = Color(0xFF004F4F)
    val tertiaryLight = Color(0xFF8E4953)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFFFD9DC)
    val onTertiaryContainerLight = Color(0xFF72333D)
    val errorLight = Color(0xFF904A43)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD5)
    val onErrorContainerLight = Color(0xFF73342D)
    val backgroundLight = Color(0xFFF7F9FF)
    val onBackgroundLight = Color(0xFF181C20)
    val surfaceLight = Color(0xFFF7FBF1)
    val onSurfaceLight = Color(0xFF181D17)
    val surfaceVariantLight = Color(0xFFDEE3EB)
    val onSurfaceVariantLight = Color(0xFF42474E)
    val outlineLight = Color(0xFF72787E)
    val outlineVariantLight = Color(0xFFC2C7CE)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2D322C)
    val inverseOnSurfaceLight = Color(0xFFEEF2E9)
    val inversePrimaryLight = Color(0xFF98CCF9)
    val surfaceDimLight = Color(0xFFD8DBD2)
    val surfaceBrightLight = Color(0xFFF7FBF1)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF1F5EC)
    val surfaceContainerLight = Color(0xFFECEFE6)
    val surfaceContainerHighLight = Color(0xFFE6E9E0)
    val surfaceContainerHighestLight = Color(0xFFE0E4DB)
    val warningLight = Color(0xFF8B5000)
    val onWarningLight = Color(0xFFFFFFFF)
    val warningContainerLight = Color(0xFFFF9800)
    val onWarningContainerLight = Color(0xFF653900)

    // Light High Contrast
    val primaryLightHighContrast = Color(0xFF002F4A)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF094D74)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF003232)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF005252)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF511823)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF75353F)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF511A15)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF76362F)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF7F9FF)
    val onBackgroundLightHighContrast = Color(0xFF181C20)
    val surfaceLightHighContrast = Color(0xFFF7FBF1)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFDEE3EB)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF272D32)
    val outlineVariantLightHighContrast = Color(0xFF444A50)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2D322C)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFF98CCF9)
    val surfaceDimLightHighContrast = Color(0xFFB6BAB2)
    val surfaceBrightLightHighContrast = Color(0xFFF7FBF1)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFEEF2E9)
    val surfaceContainerLightHighContrast = Color(0xFFE0E4DB)
    val surfaceContainerHighLightHighContrast = Color(0xFFD2D6CD)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC4C8BF)
    val warningLightHighContrast = Color(0xFF442500)
    val onWarningLightHighContrast = Color(0xFFFFFFFF)
    val warningContainerLightHighContrast = Color(0xFF6D3E00)
    val onWarningContainerLightHighContrast = Color(0xFFFFFFFF)

    // Dark
    val primaryDark = Color(0xFF98CCF9)
    val onPrimaryDark = Color(0xFF003350)
    val primaryContainerDark = Color(0xFF044B71)
    val onPrimaryContainerDark = Color(0xFFCCE5FF)
    val secondaryDark = Color(0xFF80D5D4)
    val onSecondaryDark = Color(0xFF003737)
    val secondaryContainerDark = Color(0xFF004F4F)
    val onSecondaryContainerDark = Color(0xFF9CF1F0)
    val tertiaryDark = Color(0xFFFFB2BB)
    val onTertiaryDark = Color(0xFF561D27)
    val tertiaryContainerDark = Color(0xFF72333D)
    val onTertiaryContainerDark = Color(0xFFFFD9DC)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF561E19)
    val errorContainerDark = Color(0xFF73342D)
    val onErrorContainerDark = Color(0xFFFFDAD5)
    val backgroundDark = Color(0xFF101418)
    val onBackgroundDark = Color(0xFFE0E3E8)
    val surfaceDark = Color(0xFF10140F)
    val onSurfaceDark = Color(0xFFE0E4DB)
    val surfaceVariantDark = Color(0xFF42474E)
    val onSurfaceVariantDark = Color(0xFFC2C7CE)
    val outlineDark = Color(0xFF8C9198)
    val outlineVariantDark = Color(0xFF42474E)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE0E4DB)
    val inverseOnSurfaceDark = Color(0xFF2D322C)
    val inversePrimaryDark = Color(0xFF2A638B)
    val surfaceDimDark = Color(0xFF10140F)
    val surfaceBrightDark = Color(0xFF363A34)
    val surfaceContainerLowestDark = Color(0xFF0B0F0A)
    val surfaceContainerLowDark = Color(0xFF181D17)
    val surfaceContainerDark = Color(0xFF1C211B)
    val surfaceContainerHighDark = Color(0xFF272B25)
    val surfaceContainerHighestDark = Color(0xFF323630)
    val warningDark = Color(0xFFFFC081)
    val onWarningDark = Color(0xFF4A2800)
    val warningContainerDark = Color(0xFFFF9800)
    val onWarningContainerDark = Color(0xFF653900)

    // Dark High Contrast
    val primaryDarkHighContrast = Color(0xFFE5F1FF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF94C8F5)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000C18)
    val secondaryDarkHighContrast = Color(0xFFAAFFFE)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFF7CD1D0)
    val onSecondaryContainerDarkHighContrast = Color(0xFF000E0E)
    val tertiaryDarkHighContrast = Color(0xFFFFEBEC)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFFFACB6)
    val onTertiaryContainerDarkHighContrast = Color(0xFF210006)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220000)
    val backgroundDarkHighContrast = Color(0xFF101418)
    val onBackgroundDarkHighContrast = Color(0xFFE0E3E8)
    val surfaceDarkHighContrast = Color(0xFF10140F)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF42474E)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFEBF0F8)
    val outlineVariantDarkHighContrast = Color(0xFFBEC3CA)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE0E4DB)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF074C73)
    val surfaceDimDarkHighContrast = Color(0xFF10140F)
    val surfaceBrightDarkHighContrast = Color(0xFF4D514B)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1C211B)
    val surfaceContainerDarkHighContrast = Color(0xFF2D322C)
    val surfaceContainerHighDarkHighContrast = Color(0xFF383D36)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF444841)
    val warningDarkHighContrast = Color(0xFFFFEDDF)
    val onWarningDarkHighContrast = Color(0xFF000000)
    val warningContainerDarkHighContrast = Color(0xFFFFB363)
    val onWarningContainerDarkHighContrast = Color(0xFF150800)
}